### ISSUE TITLE
Is there a plan to add function compute Jd*qd ?

### ISSUE THREAD

**Issue by ziyonghan** [ROAM-Lab-ND/spatial_v2_extended#8]
Hi Dr. Pat
As an extension of body jacobian, is there a plan to add function compute Jd*qd ? 

Best
Han

**Comment by pwensing** [comment]
Hi Han, 

Sorry for my delay. We don't have plans for this, in part because of peculiarities depending on the different coordinate frames that one might wish to use for the Jacobian and/or whether or not you're interested in linear/angular, both. 

If you are interested in $\dot{\mathbf{J}} \dot{\mathbf{q}}$ for a body Jacobian (i.e., that gives the spatial velocity of some body, in its body-fixed coordinates via ${}^i \mathbf{v}_i = \mathbf{J} \dot{\mathbf{q}}$), then it follows that ${}^i \mathbf{a}_i = \frac{{\rm d}}{{\rm d }t} {}^i \mathbf{v}_i$ in this case, and so:

$${}^i \mathbf{a}_i = \mathbf{J} \ddot{\mathbf{q}} + \dot{\mathbf{J}} \dot{\mathbf{q}}$$ 

This means that you can run the `ID` function (inverse dynamics) with $\ddot{\mathbf{q}} = 0$ and then you'll get ${}^i \mathbf{a}_i =\dot{\mathbf{J}} \dot{\mathbf{q}}$ in this case. Right now, the `ID` function doesn't output this acceleration, but it's in there. See, e.g., https://github.com/ROAM-Lab-ND/spatial_v2_extended/blob/7967e4312359f696237d12a794271c1838f763fe/v3/dynamics/ID.m#L31
So you can add `a` as an additional output if needed. 

More generally, if you have some other task-space variable that you can construct as $\boldsymbol{v}_t = \mathbf{A}(\mathbf{q}) {}^i \mathbf{v}_i$, then you'd also have to account for the time derivative of $\mathbf{A}(\mathbf{q})$, which is going to be use-case specific. For example, if you were interested in the Cartesian velocity of the frame origin, expressed in some world frame, you'd have $\mathbf{A} = \left[ \mathbf{0}\_{3 \times 3} ~ {}^0 \mathbf{R}_i \right]$ and so you'd have to account for the change in orientation. You could do this by then noting that $\dot{\mathbf{A}} =\left[ \mathbf{0}\_{3 \times 3} ~ {}^0 \mathbf{R}\_i \\! \left( {}^i \boldsymbol{\omega}_i \times \right) \right]$ where  ${}^i \boldsymbol{\omega}_i$ is the angular velocity of the frame that you could extract from the first three rows of the spatial velocity ${}^i \mathbf{v}_i$, which is itself computed within `ID`. This variation is probably the most common one beyond using the spatial Jacobian, but the variety of use cases prevents me from trying to provide a one-size-fits all solution in the interface. If you see an alternative route, please let me know, and we'd be happy to consider it. 

I hope this is helpful for you!

Best,
-Pat

**Comment by ziyonghan** [comment]
Hi Dr. Pat,
Thanks a lot for the view of task-space variable construct as `v_t = A(q)v_i`, and I get `Jdqd` in analytical way. It's much better than numerical differentiation.
For general use-case, I think `J_dot` in task-space kinematics and `A_dot` the centroid dynamics are needed for this package.

**Comment by pwensing** [comment]
Hi Han,

I went back through and found an old implementation of `J_dot` that I was able to quickly clean up, while still leaving the additional details above up to the individual user. You can find it here: 95b71b3d57481fddfc810927eaf4e1b74b9cb3e0

If you don't pass the `Xend` and `Xend_dot` arguments, then it will default to giving $\frac{d}{dt} {}^i \mathbf J_i$. The inputs `Xend` and `Xend_dot` are the equivalent of $\mathbf A(\mathbf q)$ and $\frac{d}{dt} \mathbf A(\mathbf q)$ above. 

Regarding the $\dot{\mathbf A}_G  \dot{\mathbf q}$ terms for the centroidal dynamics, I didn't realize those were missing from the library! Great catch. I added them as optional outputs to the CMM function a3cb47ad190b39f5078b69b39579a2c6a000be36

I don't think one would ever need $\dot{\mathbf A}_G$ individually, but it's easy enough, so added here too 44c96a930bb0915aced969346de276e066312f71 in case it helps.

Let me know if you have any questions about how to use these functions. At some point, I should try to document this as nicely as Roy did the original spatial_v2 pacakge, but today is not that day :)

Best,
-Pat

**Comment by ziyonghan** [comment]
Hi Dr. Pat,

Thanks a lot! I have tested the updated BodyJacobianTimeDerivative function and CMM function, it works well.

Best,
Han

**Comment by pwensing** [comment]
Excellent. Thanks for the confirmation. If you have any other feedback on the repo, please don't hesitate to reach back out.

**Comment by ziyonghan** [comment]
Hi Dr. Pat,

I have a use case where I want to calculate the Jacobian derivative of an object held in hand. The previous calculation method was to create a virtual joint at this coordinate point and then calculate the Jacobian derivative of this virtual coordinate. Now I want to pass the coordinates of the object relative to the wrist joint into the BodyJacobianTimeDerivative function.

Below is my code. When nargin>4, how should I calculate the correct BodyEnd and BodyEnd_dot information?

`function  [Jd, Jd_Lin] = get_jacobian_Jd( robot, q, qd, linkName, Xend )
% Xend, coordinate in body frame, [x y z]
% J_world_dot = blkdiag(R)_dot * J_body + blkdiag(R) * J_body_dot

if nargin > 4
    Xtree = plux(eye(3), Xend');
else
    Xtree = plux(eye(3), [0, 0, 0]');
end

% get jointNum
jointNum = 0;
jointNum = find(strcmp(robot.jointNames, linkName)); 

% get v and Xup
[~, out] = ID(robot, q, qd, zeros(size(q)));
v = out.v;
Xup = out.Xup;

% calc X
X = eye(6); 
X = X * Xtree;
j = jointNum;
while j > 0
    X = X * Xup{j};
    j = robot.parent(j);
end
[R, ~] = plux(X);

% calc Jd
Rdot = R'*skew2( v{jointNum}(1:3) );

if nargin > 4
    BodyEnd = X;
    BodyEnd_dot = blkdiag(Rdot, Rdot);
else
    BodyEnd = blkdiag(R', R');
    BodyEnd_dot = blkdiag(Rdot, Rdot);
end

Jd = BodyJacobianTimeDerivative(robot,q,qd,jointNum,BodyEnd,BodyEnd_dot);
Jd_Lin = Jd(4:end, :);
`
